version: "3.9"

services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    container_name: janken-front
    tty: true
    volumes:
      - .:/app
      # - node_modules:/app/frontend/node_modules
    ports:
      - 5173:5173
    command: yarn dev

  gcp:
    build:
      context: ./gcp/
      dockerfile: Dockerfile
    container_name: janken-gcp
    ports:
      - 8080:8080
    tty: true
    volumes:
      - .:/app
